apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-world
  namespace: argocd
spec:
  project: hello-world
  destination:
    name: microk8s-cluster
    namespace: hello-world
  sources:
    - repoURL: git@github.com:RyuunosukeDS3/hello-world-gitops.git
      path: "hello-world/k8s"
      targetRevision: main
      ref: main
      name: main
    - chart: hello-world
      repoURL: https://ryuunosukeds3.github.io/hello-world-charts
      targetRevision: "0.2.1"
      helm:
        releaseName: hello-world
        valueFiles:
          - $main/hello-world/helm/hello-world-values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
